'use client'

import { Gauge } from 'lucide-react'
import { BarList } from '@/components/charts'
import { Badge, Callout, Card, CardHeader, DescriptionList, EmptyState, ErrorState, PageHeader, Skeleton, StatCard, table } from '@/components/ui'
import { getFeatureImportance, getModelInfo } from '@/lib/api'
import { usePolling } from '@/lib/hooks'
import { cn, formatDateTime, formatNumber, formatPercent } from '@/lib/utils'
import type { ModelMetrics } from '@/types'

const MODEL_LABELS: Record<string, { name: string; role: string }> = {
  xgboost: { name: 'XGBoost', role: 'Serving' },
  lightgbm: { name: 'LightGBM', role: 'Ensemble member' },
  random_forest: { name: 'Random forest', role: 'Ensemble member' },
  ensemble: { name: 'Soft-voting ensemble', role: 'Report only' },
}

const METRICS: { key: keyof ModelMetrics; label: string; description: string }[] = [
  { key: 'roc_auc', label: 'ROC-AUC', description: 'Ranking quality across all thresholds' },
  { key: 'precision', label: 'Precision', description: 'Share of flagged transactions that were fraud' },
  { key: 'recall', label: 'Recall', description: 'Share of fraud cases that were flagged' },
  { key: 'f1', label: 'F1 score', description: 'Balance of precision and recall' },
]

const count = (value?: number) => (value === undefined ? '—' : formatNumber(value))

export default function ModelPerformance() {
  const info = usePolling(getModelInfo, 0)
  const importance = usePolling(getFeatureImportance, 0)

  const models = info.data?.models ?? {}
  const serving = models.xgboost
  const dataset = info.data?.dataset ?? {}
  const topFeatures = (importance.data ?? []).slice(0, 15)

  return (
    <div className="space-y-6">
      <PageHeader
        title="Model performance"
        description={
          info.data?.training_date
            ? `Evaluation from the training run on ${formatDateTime(info.data.training_date)}.`
            : 'Evaluation results from the last training run.'
        }
      />

      {info.error && <ErrorState message={info.error} onRetry={info.refresh} />}

      <Callout title="How to read these numbers">
        Metrics are measured on the held-out test split of the synthetic dataset generated by train_advanced_model.py. Synthetic fraud is
        easier to separate than real fraud, so expect lower scores on production data.
      </Callout>

      {info.loading && !info.data ? (
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {Array.from({ length: 4 }, (_, i) => (
            <Skeleton key={i} className="h-[118px] rounded-xl" />
          ))}
        </div>
      ) : !Object.keys(models).length ? (
        !info.error && (
          <Card>
            <EmptyState
              icon={Gauge}
              title="No evaluation report"
              description="Run python train_advanced_model.py to write reports/model_report.json, then restart the API."
            />
          </Card>
        )
      ) : (
        <>
          {serving && (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              {METRICS.map((metric) => (
                <StatCard key={metric.key} label={metric.label} value={serving[metric.key].toFixed(3)} hint={metric.description} />
              ))}
            </div>
          )}

          <Card>
            <CardHeader title="Model comparison" description="Every model trained in the last run. Only XGBoost serves predictions." />
            <div className="mt-4 overflow-x-auto">
              <table className="w-full text-left text-13">
                <thead>
                  <tr className={table.headRow}>
                    <th scope="col" className={table.th}>Model</th>
                    <th scope="col" className={table.th}>Role</th>
                    {METRICS.map((metric) => (
                      <th key={metric.key} scope="col" className={cn(table.th, 'text-right')}>
                        {metric.label}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {Object.entries(models).map(([key, metrics]) => {
                    const label = MODEL_LABELS[key] ?? { name: key, role: '—' }
                    return (
                      <tr key={key} className={table.row}>
                        <td className={cn(table.td, 'font-medium text-foreground')}>{label.name}</td>
                        <td className={table.td}>
                          {label.role === 'Serving' ? (
                            <Badge className="bg-primary/10 text-accent ring-primary/20">Serving</Badge>
                          ) : (
                            <span className="text-muted-foreground">{label.role}</span>
                          )}
                        </td>
                        {METRICS.map((metric) => (
                          <td key={metric.key} className={cn(table.td, 'text-right tabular-nums text-foreground')}>
                            {typeof metrics[metric.key] === 'number' ? metrics[metric.key].toFixed(3) : '—'}
                          </td>
                        ))}
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </Card>

          <div className="grid gap-6 lg:grid-cols-3">
            <Card className="lg:col-span-2">
              <CardHeader title="Feature importance" description="Top 15 features by XGBoost importance, as a share of the total" />
              <div className="p-5">
                {importance.error ? (
                  <p className="text-13 text-danger-fg">{importance.error}</p>
                ) : importance.loading && !importance.data ? (
                  <div className="space-y-4">
                    {Array.from({ length: 6 }, (_, i) => (
                      <Skeleton key={i} className="h-7" />
                    ))}
                  </div>
                ) : topFeatures.length ? (
                  <BarList
                    items={topFeatures.map((feature) => ({
                      key: feature.feature,
                      label: <span className="font-mono text-xs">{feature.feature}</span>,
                      value: feature.importance,
                      display: formatPercent(feature.importance),
                    }))}
                  />
                ) : (
                  <p className="text-13 text-subtle-foreground">Feature importance is unavailable for the loaded model.</p>
                )}
              </div>
            </Card>

            <Card>
              <CardHeader title="Evaluation data" description="Synthetic dataset from the last training run" />
              <div className="px-5 pb-2 pt-3">
                <DescriptionList
                  items={[
                    { label: 'Total samples', value: <span className="tabular-nums">{count(dataset.total_samples)}</span> },
                    {
                      label: 'Fraud rate',
                      value: <span className="tabular-nums">{dataset.fraud_rate === undefined ? '—' : formatPercent(dataset.fraud_rate)}</span>,
                    },
                    { label: 'Training samples', value: <span className="tabular-nums">{count(dataset.train_samples)}</span> },
                    { label: 'Test samples', value: <span className="tabular-nums">{count(dataset.test_samples)}</span> },
                    { label: 'Features', value: <span className="tabular-nums">{count(dataset.features)}</span> },
                  ]}
                />
              </div>
            </Card>
          </div>
        </>
      )}
    </div>
  )
}
